language: node_js
node_js:
  - lts/*
os: linux
branches:
  only:
    - master
jobs:
  include:
    - stage: jest test
      script: npm test
notifications:
  slack:
    on_success: never
    on_failure: always